// Generated by CoffeeScript 1.6.3
(function() {
  var app, express;

  console.log("Hello BackboneORM");

  if (typeof window === "undefined" || window === null) {
    express = require('express');
    app = express();
    app.use(express.bodyParser());
    app.use(express["static"](__dirname));
    app.get('/', function(req, res) {
      return res.sendfile('./index.html');
    });
    app.listen(3000);
  }

}).call(this);
